// Testimonials
export const FETCH_TESTIMONIALS = 'FETCH_TESTIMONIALS';
export const SET_TESTIMONIALS = 'SET_TESTIMONIALS';

// Calculator
export const FETCH_CALCULATOR_DATA = 'FETCH_CALCULATOR_DATA';
export const SET_CALCULATOR_DATA = 'SET_CALCULATOR_DATA';
export const CALCULATE_ESTIMATED_COSTS = 'CALCULATE_ESTIMATED_COSTS';
